log_level: 10
meta_items_filepath: data/items.csv
donations_filepath: data/donorschoose.org/Donations.csv
projects_filepath: data/donorschoose.org/Projects.csv
donors_filepath: data/donorschoose.org/Donors.csv
schools_filepath: data/donorschoose.org/Schools.csv
output_filepath: data/meta-learner-items.csv
random_state_seed: 2718281828
algorithms_name:
    - SciPy-SVD
    - SKLearn-SVD
    - SKLearn-KNN
    - SKLearn-NMF
    - Tfidf
    - FastText
algorithms_accuracy_name: ['RecallAtPosition']
# Process by which to select the algorithm from the learning subsystem; a subsect of {'classification', 'accuracy prediction'}
algorithm_selection_methods:
    - classification
    - accuracy prediction
n_splits: 1
train_size: 0.8
meta_algorithms_args:
    AdaBoost:
        model: SKLearn-AdaBoostClassifier
        options: {}
    Bagging:
        model: SKLearn-BaggingClassifier
        options: {}
    ExtraTrees:
        model: SKLearn-ExtraTreesClassifier
        options: {}
    GradientBoosting:
        model: SKLearn-GradientBoostingClassifier
        options: {}
    RandomForest:
        model: SKLearn-RandomForestClassifier
        options: {}
    DecisionTree:
        model: SKLearn-DecisionTreeClassifier
        options: {}
    ExtraTree:
        model: SKLearn-ExtraTreeClassifier
        options: {}
    NeuralNetwork:
        model: Keras-NN
        options:
            epochs: 50
            batch_size: 256
            optimizer: adadelta
            loss: categorical_crossentropy
            metrics: ['accuracy']
            verbose: 1
